(function(global, doc){
  'use strict';
  var EVENT_NAME = 'ag:screen-change';
  var HIDDEN_CTA_CLASS = 'detailCta--calculatorHidden';
  var shell = null, detailCta = null, detailObserver = null, booted = false, loadPromise = null, lastScreen = 'catalog';
  function siteUrl(path){ try { var env = global.__SITE_ENV__ || null; if (env && typeof env.resolveSiteUrl === 'function') return env.resolveSiteUrl(path); } catch (_) {} try { return new URL(String(path || '').replace(/^\/+/ , ''), global.location.href).toString(); } catch (_) { return path; } }
  function getMount(screen){ return screen === 'detail' ? doc.getElementById('calculatorModuleDetailMount') : doc.getElementById('calculatorModuleCatalogMount'); }
  function getDetailCta(){ if (detailCta && detailCta.isConnected) return detailCta; detailCta = doc.getElementById('detailCta') || doc.querySelector('#screenDetail .detailCta'); return detailCta; }
  function setDetailCtaHidden(hidden){ var cta = getDetailCta(); if (cta) cta.classList.toggle(HIDDEN_CTA_CLASS, !!hidden); }
  function detectActiveScreen(){ var detail = doc.getElementById('screenDetail'); if (detail && detail.classList.contains('screen--active') && !detail.hasAttribute('hidden')) return 'detail'; return 'catalog'; }
  function ensureInlineStyles(){ if (doc.getElementById('calculatorEmbedInlineStyles')) return; var style = doc.createElement('style'); style.id = 'calculatorEmbedInlineStyles'; style.textContent = ['.calculatorEmbed--inline{overflow:visible !important;}','.calculatorEmbed__body{padding:0;background:#f8fafc;}','.calculatorEmbed__body > #paverConf2026{margin:0;max-width:none;border:0;border-radius:0;box-shadow:none;}','.calculatorEmbed__body > .pcFormLightbox{z-index:140;}','.calculatorEmbed__body > .pcMobileBar{z-index:120;}','@media (max-width:760px){.calculatorEmbed__body > #paverConf2026{border-radius:0;}}'].join('\n'); (doc.head || doc.documentElement).appendChild(style); }
  function loadScript(src, parent){ return new Promise(function(resolve, reject){ var script = doc.createElement('script'); script.src = src; script.async = false; script.onload = function(){ resolve(script); }; script.onerror = function(){ reject(new Error('script-load-failed:' + src)); }; parent.appendChild(script); }); }
  function ensureCalculatorLoaded(){ if (global.__paverConfiguratorEmbedLoaded && doc.getElementById('paverConf2026')) return Promise.resolve(); if (loadPromise) return loadPromise; ensureInlineStyles(); global.__AG_CALCULATOR_ASSET_BASE__ = siteUrl('calculator_module/'); var body = shell.querySelector('.calculatorEmbed__body'); loadPromise = loadScript(siteUrl('calculator_module/config.js?v=20260422-f24do'), body).then(function(){ return loadScript(siteUrl('calculator_module/paver-configurator-core.js?v=20260422-f24do'), body); }).then(function(){ return loadScript(siteUrl('calculator_module/bridge.js?v=20260422-f24do'), body); }).then(function(){ if (detailObserver && shell) { try { detailObserver.disconnect(); } catch (_) {} detailObserver.observe(shell); } }); return loadPromise; }
  function createShell(){ if (shell) return shell; shell = doc.createElement('section'); shell.className = 'calculatorEmbed calculatorEmbed--inline'; shell.innerHTML = '<div class="calculatorEmbed__head"><div class="calculatorEmbed__title">Калькулятор стоимости</div></div><div class="calculatorEmbed__body"><div id="paverConf2026"></div></div>'; ensureDetailObserver(); return shell; }
  function moveTo(screen){ var mount = getMount(screen); if (!mount) return; createShell(); if (shell.parentNode !== mount) mount.appendChild(shell); lastScreen = screen; if (screen !== 'detail') setDetailCtaHidden(false); ensureCalculatorLoaded(); }
  function ensureDetailObserver(){ if (detailObserver || !global.IntersectionObserver) return; detailObserver = new global.IntersectionObserver(function(entries){ var shouldHideDetailCta = false; for (var i = 0; i < entries.length; i += 1) { var entry = entries[i]; if (entry.target !== shell) continue; shouldHideDetailCta = !!(entry.isIntersecting && entry.intersectionRatio >= 0.18); } if (lastScreen === 'detail') setDetailCtaHidden(shouldHideDetailCta); else setDetailCtaHidden(false); }, { threshold: [0, 0.05, 0.18, 0.35, 0.55] }); if (shell) detailObserver.observe(shell); }
  function init(){ if (booted) return; if (!doc.getElementById('calculatorModuleCatalogMount') || !doc.getElementById('calculatorModuleDetailMount')) return; booted = true; moveTo(detectActiveScreen()); global.addEventListener(EVENT_NAME, function(ev){ var screen = ev && ev.detail && ev.detail.screen ? ev.detail.screen : detectActiveScreen(); if (screen === 'catalog' || screen === 'detail') moveTo(screen); else setDetailCtaHidden(false); }); }
  if (doc.readyState === 'loading') doc.addEventListener('DOMContentLoaded', init, { once: true }); else init();
})(window, document);
